name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build_and_push:
    permissions:
      id-token: write
      contents: read
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: 'actions/checkout@v3'
      
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Use gcloud CLI
      run: gcloud info
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: projects/118785805795/locations/global/workloadIdentityPools/wif-test/subject/gitaction-test
        service_account: 'test-gcp@erudite-pod-391005.iam.gserviceaccount.com'
        audience: 'https://github.com/qpqpqp1224/test'
        
    - name: Build the Docker image
      run: docker build -t asia-northeast3-docker.pkg.dev/erudite-pod-391005/test/test822-app:v1 .

    - name: auth repository
      run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev/erudite-pod-391005/test

    - name: image exists check
      run: docker images
      
    - name: Upload Docker image
      run: docker push asia-northeast3-docker.pkg.dev/erudite-pod-391005/test/test822-app:v1
