name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  
  workload-identity-connection:
   
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write
      
  build:  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: erudite-pod-391005/locations/global/workloadIdentityPools/wif-test/providers/gitaction-test'
        service_account: test-gcp@erudite-pod-391005.iam.gserviceaccount.com
        
    - name: Build the Docker image
      run: docker build -t asia-northeast3-docker.pkg.dev/erudite-pod-391005/test/test822-app:v1 .

    - name: auth repository
      run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev/erudite-pod-391005/test

    - name: image exists check
      run: docker images
      
    - name: Upload Docker image
      run: docker push asia-northeast3-docker.pkg.dev/erudite-pod-391005/test/test822-app:v1
