name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with: 
        workload_identity_provider: gitaction-test
        service_account: test-gcp@erudite-pod-391005.iam.gserviceaccount.com

    - name: Build the Docker image
      run: docker build -t asia-northeast3-docker.pkg.dev/erudite-pod-391005/test/test822-app:v1 .

    - name: Build the Docker image
      run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev/erudite-pod-391005/test

    - name: Build the Docker image
      run: docker images
      
    - name: Build the Docker image
      run: docker push asia-northeast3-docker.pkg.dev/erudite-pod-391005/test/test822-app:v1
