name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build_and_push:
    permissions:
      contents: read
      id-token: write

   runs-on: ubuntu-latest

    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Use gcloud CLI
      run: gcloud info
      
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'erudite-pod-391005/locations/global/workloadIdentityPools/wif-test/providers/gitaction-test'
        service_account: 'test-gcp@erudite-pod-391005.iam.gserviceaccount.com'
        audience: 'https://github.com/qpqpqp1224/test'
        
    - name: Build the Docker image
      run: docker build -t asia-northeast3-docker.pkg.dev/erudite-pod-391005/test/test822-app:v1 .

    - name: auth repository
      run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev/erudite-pod-391005/test

    - name: image exists check
      run: docker images
      
    - name: Upload Docker image
      run: docker push asia-northeast3-docker.pkg.dev/erudite-pod-391005/test/test822-app:v1
