name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t asia-northeast3-docker.pkg.dev/erudite-pod-391005/test/test822:v1 .

    - name: Build the Docker image
      run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev 
      
    - name: Build the Docker image
      run: docker push asia-northeast3-docker.pkg.dev/erudite-pod-391005/test/test822:v1
