name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

env:
  LOCATION: asia-northeast3
  PROJECT_ID: trans-shuttle-401410
  REPOSITORY: test
  IMAGE_NAME: test_canary
  TAG: 2.0.0
  PROVIDER_ID: projects/400645327499/locations/global/workloadIdentityPools/gitaction/providers/gitaction
  SERVICE_ACCOUNT: serviceaccount-test@trans-shuttle-401410.iam.gserviceaccount.com
  AUDIENCE: https://github.com/qpqpqp1224/test
    
jobs:
  build_and_push:
    permissions:
      id-token: write
      contents: read
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: 'actions/checkout@v3'
      
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ env.PROVIDER_ID }}'
        service_account: '${{ env.SERVICE_ACCOUNT }}'
        audience: '${{ env.AUDIENCE }}'  
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.1

    - name: Use gcloud CLI
      run: gcloud info

    - name: Docker configuration
      run: |
        echo "${{ steps.auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://${{ env.LOCATION }}-docker.pkg.dev
        
    - name: Build the Docker image
      run: docker build -t ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

    - name: auth repository
      run: gcloud auth configure-docker "${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"

    - name: image exists check
      run: docker images
    
    - name: Upload Docker image
      run: docker push "${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
      
